name: Docker CI Pipeline
on:
  push:
    branches: [ main ]

jobs:
  docker_build_deploy:   
    name: Docker Build & Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login to Docker hub
        uses: docker/login-action@v2
        with:
          username: sooscode
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: docker build -t sooscode/flask-app_lives:v2 .

      - name: Push Docker image
        run: docker push sooscode/flask-app_lives:v2

      - name: Deploy locally
        run: powershell -ExecutionPolicy Bypass -File ".\deploy.ps1"
